# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-01 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=90)),
                ('email', models.CharField(max_length=45)),
                ('alias', models.CharField(default=' ', max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friended', models.ManyToManyField(related_name='_user_friended_+', to='login.User')),
            ],
        ),
    ]
